### ISSUE TITLE
【每日打卡】2020.04.14

### ISSUE THREAD

**Issue by gengmingOrg** [JTDI/leetcode-practice#8]
21. 合并两个有序链表
将两个升序链表合并为一个新的升序链表并返回。新链表是通过拼接给定的两个链表的所有节点组成的。 
图解：
![image](https://user-images.githubusercontent.com/32930894/79177953-8a30a900-7e36-11ea-97e8-ae5eff970cad.png)

**Comment by jay0815** [comment]
445. 两数相加 II
![image](https://user-images.githubusercontent.com/16587728/79191487-48652a00-7e59-11ea-94b1-53ce907357a0.png)

![image](https://user-images.githubusercontent.com/16587728/79191465-384d4a80-7e59-11ea-96ea-6fdbfbdd7cc9.png)
[LeetCode Link](https://leetcode-cn.com/problems/add-two-numbers-ii/)

**Comment by mosiya** [comment]
53.最大子序和
![1586851911063](https://user-images.githubusercontent.com/11433873/79202083-a438ae80-7e6b-11ea-97c8-8712f7ea79dd.jpg)

说明描述：
1、记录一个子序列和sum，在遍历下一个数时，先进行加和计算并储存结果。若当前加和小于0，则重置计算器。这样会记录每一次加和的结果，并且会打断小于0的结果的累加，只有大于等于0的加和是有效的。 最后对这个数组进行求最大值运算得到结果
2、Kadane算法也是类似的，只是不会进行每次结果的储存，只保存当前加和最大的数，省下了一个数组的空间
3、最后的做法，是看到了不额外开启空间的做法，我按自己的理解又重新写了一个解法，相当于第一个解法，只是将每次累加的结果直接存在了原数组里

![1586851998975](https://user-images.githubusercontent.com/11433873/79202108-ae5aad00-7e6b-11ea-9c56-1965b6cca1db.jpg)

**Comment by lyn-ho** [comment]
[94.二叉树的中序遍历](https://github.com/lyn-ho/leetcode/blob/master/medium/94.%E4%BA%8C%E5%8F%89%E6%A0%91%E7%9A%84%E4%B8%AD%E5%BA%8F%E9%81%8D%E5%8E%86.js)

![](https://tva1.sinaimg.cn/large/007S8ZIlly1gdti800nbyj30u01hzqc3.jpg)

**Comment by nation-blue** [comment]
7. 整数反转
[详情](https://mp.weixin.qq.com/s/HuN4LawTWH0-PgppQt2iOg)

**Comment by xingkai17** [comment]
7. 整数反转
![image](https://user-images.githubusercontent.com/7419238/79224370-8b40f500-7e8d-11ea-838c-a27115161030.png)

**Comment by amandafanny** [comment]
10. 正则表达式匹配
![image](https://user-images.githubusercontent.com/54808661/79231335-7b7ade00-7e98-11ea-95da-84bef6299493.png)

https://blog.csdn.net/lxcnn/article/details/4756030

**Comment by ZQF-KINGKONG** [comment]
2.两数相加
链表
https://leetcode-cn.com/problems/add-two-numbers/solution/liang-shu-xiang-jia-by-zqf-2/

**Comment by luchaohai** [comment]
66.加一
大数进位：用数组实现的链表题，大数的存储结构
![code](https://user-images.githubusercontent.com/11420885/79246718-28128b00-7eac-11ea-9669-8896b37e3702.png)

**Comment by ZQF-KINGKONG** [comment]
445.两数相加
链表反转/栈实现逆序
https://leetcode-cn.com/problems/add-two-numbers-ii/solution/liang-shu-xiang-jia-by-zqf-2-2/

**Comment by RamboGit** [comment]
189.旋转数组
解题思路一：暴力破解，时间复杂度随着 k 的升高而升高 O(n*k)
<img width="1239" alt="截屏2020-04-15 上午5 34 14" src="https://user-images.githubusercontent.com/15643844/79281880-4d23ef80-7ee6-11ea-9969-aa6c08a0fbf7.png">
解题思路二：看别人题解通过反转数组，时间复杂度 O(n),加上了临界条件
<img width="1231" alt="截屏2020-04-15 上午6 51 37" src="https://user-images.githubusercontent.com/15643844/79282048-c15e9300-7ee6-11ea-83ec-bb0e91276a3a.png">

**Comment by monstereat** [comment]
26. 删除排序数组中的重复项
![image](https://user-images.githubusercontent.com/13077554/79304704-8418f600-7f24-11ea-9423-394639545a2f.png)
